name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

env:
  CARGO_TERM_COLOR: always

jobs:
  build-website:
    runs-on: ubuntu-latest
    concurrency: build-website-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Build website
        run: ./build.sh

      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: public

      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          folder: public
          force: false
          clean-exclude: pr-preview

  cleanup-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v4

      - name: Cleanup preview
        uses: rossjrw/pr-preview-action@v1
        with:
          action: remove
